/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nick Broad (https://sketchfab.com/nickbroad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/golf-r32-8171332b39be45e896a7fdf3c3e66354
title: Golf R32
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../utils/angles';

export default function Car({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/car/model-transformed.glb')
  return (
    <group 
			ref={group} {...props} dispose={null} scale={0.009} position={[0, -0.009, -3]} rotation={[0, angleToRadians(-50), 0]}
			onClick={() => console.log('clicked')}
		>
      <group position={[0, 9.82, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 54.99, 177.3]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.18, 9.18, 27.77]}>
            <mesh castShadow receiveShadow geometry={nodes.GrillTop011_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.BumperFront_Cut034_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 72.93, 130.27]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Bonnet017_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 35.35, 175.61]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.18, 9.18, 13.88]}>
            <mesh castShadow receiveShadow geometry={nodes.GrillBack011_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.FrontWing012_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 41.34, 176.53]} rotation={[-1.6, 0, 0]} scale={10.39}>
            <mesh castShadow receiveShadow geometry={nodes.LicenseFront022_LicenseWhite_0.geometry} material={materials.LicenseWhite} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.QuarterAndRoof011_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Doors011_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.WiperTrim011_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Spoiler011_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Tailgate011_Paint2_0.geometry} material={materials.Paint2} />
            <mesh castShadow receiveShadow geometry={nodes.Tailgate011_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.Tailgate011_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[0, 44.34, -184.13]} rotation={[-1.53, 0, Math.PI]} scale={10.39}>
            <mesh castShadow receiveShadow geometry={nodes.LicenseFront023_LicenseYellow_0.geometry} material={materials.LicenseYellow} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.BumperBack012_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.WindowRubber011_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.WindowRubberRear011_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[80.52, 84.43, 43.6]} rotation={[-Math.PI / 2, 0, 0.28]} scale={[5.06, 3.79, 5.06]}>
            <mesh castShadow receiveShadow geometry={nodes.WingMirror022_PlasticBlack_0.geometry} material={materials.PlasticBlack} />
            <mesh castShadow receiveShadow geometry={nodes.WingMirror022_Mirror_0.geometry} material={materials.Mirror} />
            <mesh castShadow receiveShadow geometry={nodes.WingMirror022_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 54.8, 173.13]} scale={5.15}>
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front077_BlackGloss_0.geometry} material={materials.BlackGloss} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front077_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front077_Paint2_0.geometry} material={materials.Paint2} />
          </group>
          <group position={[0, 75.57, -177.13]} rotation={[-Math.PI, 0, Math.PI]} scale={5.13}>
            <mesh castShadow receiveShadow geometry={nodes.Badge_back011_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.Badge_back011_BlackGloss_0.geometry} material={materials.BlackGloss} />
          </group>
          <group position={[39.87, 20.54, -185.15]} rotation={[-Math.PI, 0, 0]} scale={5.07}>
            <mesh castShadow receiveShadow geometry={nodes.Exhaust011_Exhaust_0.geometry} material={materials.Exhaust} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_Rubber_0.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_TaillightRedDeep_0.geometry} material={materials.TaillightRedDeep} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_TaillightAmber_0.geometry} material={materials.TaillightAmber} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_TaillightInside_0.geometry} material={materials.TaillightInside} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_RedStripes_0.geometry} material={materials.RedStripes} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_GlassTaillight_0.geometry} material={materials.GlassTaillight} />
            <mesh castShadow receiveShadow geometry={nodes.TailLightInner011_GlassTaillightAmber_0.geometry} material={materials.GlassTaillightAmber} />
          </group>
          <group position={[51.03, 54.89, 167.82]} rotation={[-1.75, -0.07, -0.05]} scale={4.93}>
            <mesh castShadow receiveShadow geometry={nodes.Headlight_inner011_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.Headlight_inner011_Glass_0.geometry} material={materials.Glass} />
            <mesh castShadow receiveShadow geometry={nodes.Headlight_inner011_ChromeAmber_0.geometry} material={materials.ChromeAmber} />
            <mesh castShadow receiveShadow geometry={nodes.Headlight_inner011_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[0, 39.28, 128.14]} rotation={[-Math.PI / 2, 0, 0]} scale={43.87}>
            <mesh castShadow receiveShadow geometry={nodes.Underbody006_Rubber_0.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Underbody006_BlackGloss_0.geometry} material={materials.BlackGloss} />
          </group>
          <group position={[-23.79, 54.97, 178.63]} rotation={[0.09, -0.02, -0.03]} scale={0.58}>
            <mesh castShadow receiveShadow geometry={nodes.BadgeR32017_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.BadgeR32017_BlackGloss_0.geometry} material={materials.BlackGloss} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.BumperFront_Cut030_FrontBumper_0.geometry} material={materials.FrontBumper} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.FrontWing011_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Tyre_low023_TyreTread_0.geometry} material={materials.TyreTread} />
            <mesh castShadow receiveShadow geometry={nodes.Tyre_low023_TyreWall_0.geometry} material={materials.TyreWall} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_Paint_0.geometry} material={materials.Paint} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_GlassHeadlight_0.geometry} material={materials.GlassHeadlight} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_Wheel_0.geometry} material={materials.Wheel} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_BlackGloss_0.geometry} material={materials.BlackGloss} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_BrakeDisc_0.geometry} material={materials.BrakeDisc} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_BrakeDiscInner_0.geometry} material={materials.BrakeDiscInner} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_Chrome001_0.geometry} material={materials['Chrome.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Badge2_front078_BrakeCaliber_0.geometry} material={materials.BrakeCaliber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_Wheel_0.geometry} material={materials.Wheel} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_BrakeDisc_0.geometry} material={materials.BrakeDisc} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_BrakeDiscInner_0.geometry} material={materials.BrakeDiscInner} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_Chrome001_0.geometry} material={materials['Chrome.001']} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_Paint_0.geometry} material={materials.Paint} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_Chrome_0.geometry} material={materials.Chrome} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_GlassHeadlight_0.geometry} material={materials.GlassHeadlight} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_BrakeCaliber_0.geometry} material={materials.BrakeCaliber} />
            <mesh castShadow receiveShadow geometry={nodes.WheelRimBack012_BlackGloss_0.geometry} material={materials.BlackGloss} />
          </group>
          <group position={[68.85, 26.35, -122.88]} rotation={[0.88, 0.03, 0.03]} scale={[65.53, 81.49, 81.49]}>
            <mesh castShadow receiveShadow geometry={nodes.Tyre_low024_TyreTread_0.geometry} material={materials.TyreTread} />
            <mesh castShadow receiveShadow geometry={nodes.Tyre_low024_TyreWall_0.geometry} material={materials.TyreWall} />
          </group>
          <group position={[34.35, 76.91, -37.67]} rotation={[-1.8, 0, 0]} scale={7.66}>
            <mesh castShadow receiveShadow geometry={nodes.Cube065_Seat_0.geometry} material={materials.Seat} />
            <mesh castShadow receiveShadow geometry={nodes.Cube065_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Windows011_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.WindowsRear011_GlassTinted_0.geometry} material={materials.GlassTinted} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.Windscreen011_GlassBlack_0.geometry} material={materials.GlassBlack} />
            <mesh castShadow receiveShadow geometry={nodes.Windscreen011_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[0, 72.93, 128.55]} rotation={[-Math.PI / 2, 0, 0]} scale={44.98}>
            <mesh castShadow receiveShadow geometry={nodes.WindscreenRear011_GlassTinted_0.geometry} material={materials.GlassTinted} />
            <mesh castShadow receiveShadow geometry={nodes.WindscreenRear011_GlassBlack_0.geometry} material={materials.GlassBlack} />
            <mesh castShadow receiveShadow geometry={nodes.WindscreenRear011_GlassHeater_0.geometry} material={materials.GlassHeater} />
          </group>
          <group position={[51.03, 54.89, 171.99]} rotation={[-1.75, -0.07, -0.05]} scale={4.93}>
            <mesh castShadow receiveShadow geometry={nodes.Headlight_glass011_GlassHeadlight_0.geometry} material={materials.GlassHeadlight} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.BumperFront_Cut032_Grill_0.geometry} material={materials.Grill} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
